name: Disable Require Status Checks

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  disable-status-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh jq

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Fetch Branch Protection Settings
        id: fetch
        run: |
          gh api "repos/${{ github.repository }}/branches/main/protection" > protection.json
          cat protection.json

      - name: Disable Require Status Checks
        run: |
          jq -e '.required_status_checks' protection.json
          if [ $? -eq 0 ]; then
            ENFORCE_ADMINS=$(jq '.enforce_admins.enabled' protection.json)
            PR_REVIEW=$(jq '.required_pull_request_reviews' protection.json)
            RESTRICTIONS=$(jq '.restrictions' protection.json)

            gh api -X PUT "repos/${{ github.repository }}/branches/main/protection" \
              -H "Accept: application/vnd.github+json" \
              -F required_status_checks.strict=false \
              -F required_status_checks.contexts='[]' \
              -F enforce_admins=$ENFORCE_ADMINS \
              -F required_pull_request_reviews="$PR_REVIEW" \
              -F restrictions="$RESTRICTIONS"
          else
            echo "No required status checks found to disable."
          fi
