name: Disable Require Status Checks

on:
  workflow_dispatch:  # Allows manual triggering
  # You can also trigger on other events like push or schedule
  # schedule:
  #   - cron: "0 0 * * 1"  # Runs every Monday at 00:00 UTC

jobs:
  disable-status-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Get Current Branch Protection Settings
        id: current-settings
        run: |
          gh api "repos/${{ github.repository }}/branches/main/protection" > protection.json || echo '{"required_status_checks": null}' > protection.json
        continue-on-error: true

      - name: Update Branch Protection
        if: steps.current-settings.outputs.status == 200
        run: |
          gh api -X PUT "repos/${{ github.repository }}/branches/main/protection" \
            -F required_status_checks.strict=false \
            -F required_status_checks.contexts='[]' \
            -F enforce_admin
