name: Disable Require Status Checks

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  disable-status-checks:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          Invoke-WebRequest -Uri https://github.com/cli/cli/releases/download/v2.41.0/gh_2.41.0_windows_amd64.msi -OutFile gh-cli.msi
          Start-Process msiexec.exe -ArgumentList '/i', 'gh-cli.msi', '/quiet', '/norestart' -Wait

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Fetch Branch Protection Settings
        id: fetch
        run: gh api "repos/${{ github.repository }}/branches/main/protection" > protection.json

      - name: Debug - Display Protection Settings
        run: Get-Content protection.json

      - name: Disable Require Status Checks
        run: |
          # Read the current branch protection settings
          $protection = Get-Content protection.json | ConvertFrom-Json

          # Construct the JSON input to disable required status checks
          $jsonInput = @{
              required_status_checks = @{
                  strict = $false
                  contexts = @()
              }
              enforce_admins = @{
                  enabled = $false
              }
              required_pull_request_reviews = $protection.required_pull_request_reviews
              restrictions = $protection.restrictions
          } | ConvertTo-Json -Compress

          # Create a temporary file to store the JSON input
          $tempFile = New-TemporaryFile
          Set-Content -Path $tempFile -Value $jsonInput

          # Display the JSON input for debugging purposes
          Write-Host "Updating branch 
