name: Disable Require Branches to be up to date

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  disable-branch-up-to-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI and jq
        run: sudo apt-get update && sudo apt-get install -y gh jq

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Fetch Branch Protection Settings
        id: fetch
        run: |
          gh api "repos/${{ github.repository }}/branches/main/protection" > protection.json
          cat protection.json

      - name: Disable Require Branches to be up to date
        run: |
          if jq -e '.required_status_checks' protection.json > /dev/null; then
            ENFORCE_ADMINS=$(jq '.enforce_admins.enabled' protection.json)
            PR_REVIEW=$(jq '.required_pull_request_reviews' protection.json)
            RESTRICTIONS=$(jq '.restrictions' protection.json)

            gh api -X PATCH "repos/${{ github.repository }}/branches/main/protection/required_status_checks" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Content-Type: application/json" \
              -d '{"include_admins":'$ENFORCE_ADMINS', "required_pull_request_reviews":'$PR_REVIEW', "restrictions":'$RESTRICTIONS'}'
          else
            echo "No required branches to be up to date found to disable."
          fi
