name: Disable Require Status Checks

on:
  workflow_dispatch:  # Allows manual triggering
  # You can also trigger on other events like push or schedule
  # schedule:
  #   - cron: "0 0 * * 1"  # Runs every Monday at 00:00 UTC

jobs:
  disable-status-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"

      - name: Disable require status checks
        run: |
          gh api -X PATCH "repos/${{ github.repository }}/branches/main/protection" \
            -F required_status_checks.required=false \
            -F required_status_checks.contexts='[]'
