name: Disable Require Status Checks

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  disable-status-checks:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          Invoke-WebRequest -Uri https://github.com/cli/cli/releases/download/v2.41.0/gh_2.41.0_windows_amd64.msi -OutFile gh-cli.msi
          Start-Process msiexec.exe -ArgumentList '/i', 'gh-cli.msi', '/quiet', '/norestart' -Wait

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Fetch Branch Protection Settings
        id: fetch
        run: gh api "repos/${{ github.repository }}/branches/main/protection" > protection.json

      - name: Disable Require Status Checks
        run: |
          $protection = Get-Content protection.json | ConvertFrom-Json

          $jsonInput = @{
              required_status_checks = @{
                strict = $false
                contexts = @()
              }
          } | ConvertTo-Json -Compress

          $tempFile = New-TemporaryFile
          Set-Content -Path $tempFile -Value $jsonInput

          Write-Host "Updating branch protection with:"
          Get-Content $tempFile

          $response = gh api -X PATCH "repos/${{ github.repository }}/branches/main/protection" `
            -H "Accept: application/vnd.github.v3+json" `
            --input $tempFile

          Write-Host "GitHub API Response:"
          Write-Host $response

          Remove-Item -Path $tempFile
