name: Disable Require Status Checks

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  disable-status-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Fetch Branch Protection Settings
        id: fetch
        run: |
          gh api "repos/${{ github.repository }}/branches/main/protection" > protection.json
          cat protection.json

      - name: Disable Require Status Checks
        id: disable
        run: |
          if jq -e '.required_status_checks' protection.json; then
            gh api -X PUT "repos/${{ github.repository }}/branches/main/protection" \
              -F required_status_checks.contexts='[]' \
              -F required_status_checks.strict=false \
              -F enforce_admins=$(jq -r '.enforce_admins.enabled' protection.json) \
              -F required_pull_request_reviews=$(jq '.required_pull_request_reviews' protection.json) \
              -F restrictions=$(jq '.restrictions' protection.json)
          else
            echo "No status checks found to disable."
          fi
