name: Disable Require Branches to be up to date

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  disable-branch-up-to-date:
    runs-on: windows-latest  # Specify the Windows agent

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI and jq
        run: |
          choco install jq -y  # Install jq using Chocolatey
          choco install gh -y  # Install GitHub CLI using Chocolatey

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Fetch Branch Protection Settings
        id: fetch
        run: |
          gh api "repos/${{ github.repository }}/branches/main/protection" > protection.json
          Get-Content protection.json

      - name: Disable Require Branches to be up to d
