name: Uncheck Require Status Checks

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  uncheck-status-checks:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install GitHub CLI and jq
        run: |
          choco install jq
          choco install gh

      - name: Authenticate GitHub CLI
        run: echo ${{ secrets.GH_TOKEN }} | gh auth login --with-token

      - name: Fetch Branch Protection Settings
        id: fetch
        run: |
          gh api "repos/${{ github.repository }}/branches/main/protection" > protection.json
          type protection.json

      - name: Uncheck Require Status Checks
        responseData do several so Contains What  Adjust
